name: Bug report
description: Create a report to help us improve
labels: [bug]
title: "fix: <brief description>"
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide detailed steps to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or logs
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: OS, Node version, Browser
  - type: textarea
    id: notes
    attributes:
      label: Additional context
