// Centralized job categories list to keep PostJob form and other UI components in sync.
// Update this file to add/remove categories; import wherever needed.

export const JOB_CATEGORIES = [
  // Core existing categories
  "Graphics & Design",
  "Mobile App Development",
  "Frontend Web Development",
  "Backend Development",
  "Full Stack Development",
  "MERN Stack Development",
  "MEAN Stack Development",
  "MEVN Stack Development",
  "Account & Finance",
  "Artificial Intelligence",
  "Machine Learning",
  "Data Science",
  "Data Engineering",
  "DevOps & Cloud",
  "Cyber Security",
  "Blockchain & Web3",
  "Game Development",
  "Embedded Systems",
  "IoT (Internet of Things)",
  "UI/UX Design",
  "Video Animation",
  "AR/VR Development",
  "Quality Assurance / Testing",
  "Product Management",
  "Project Management",
  "Technical Writing",
  "Sales & Business Development",
  "Marketing & SEO",
  "Human Resources",
  "Customer Support",
  "Data Entry Operator",
  "Healthcare Tech",
  "EdTech",
  "FinTech",
  "Legal & Compliance",
  "Research & Analytics",
  "Supply Chain & Logistics",
  "Operations",
  "Consulting",
  "Content Creation & Media",
  "Copywriting",
  "Open Source Contribution",
];
